/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zlw_jnidemo_Person */

#ifndef _Included_com_example_zlw_jnidemo_Person
#define _Included_com_example_zlw_jnidemo_Person
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zlw_jnidemo_Person
 * Method:    accessGetUUID
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_example_zlw_jnidemo_Person_accessGetUUID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
